// <auto-generated />
using System;
using ContosoDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContosoDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ContosoDashboard.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 1,
                            Content = "Welcome to the new ContosoDashboard application. This platform will help you manage your tasks and projects more efficiently.",
                            CreatedByUserId = 1,
                            ExpiryDate = new DateTime(2026, 5, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3420),
                            IsActive = true,
                            PublishDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3420),
                            Title = "Welcome to ContosoDashboard"
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentShare", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("SharedWithUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SharedByUserId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId", "SharedWithUserId");

                    b.ToTable("DocumentShares");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TargetCompletionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("Status");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreatedDate = new DateTime(2026, 3, 9, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3330),
                            Description = "Internal employee productivity dashboard",
                            Name = "ContosoDashboard Development",
                            ProjectManagerId = 2,
                            StartDate = new DateTime(2026, 3, 9, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3320),
                            Status = 1,
                            TargetCompletionDate = new DateTime(2026, 6, 7, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3330),
                            UpdatedDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3330)
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");

                    b.HasData(
                        new
                        {
                            ProjectMemberId = 1,
                            AssignedDate = new DateTime(2026, 3, 9, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3390),
                            ProjectId = 1,
                            Role = "TeamLead",
                            UserId = 3
                        },
                        new
                        {
                            ProjectMemberId = 2,
                            AssignedDate = new DateTime(2026, 3, 9, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3390),
                            ProjectId = 1,
                            Role = "Developer",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 3, 9, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3360),
                            Description = "Create entity relationship diagram and database design",
                            DueDate = new DateTime(2026, 3, 19, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3350),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Design database schema",
                            UpdatedDate = new DateTime(2026, 3, 19, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3360)
                        },
                        new
                        {
                            TaskId = 2,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 3, 14, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3360),
                            Description = "Set up Microsoft Entra ID authentication",
                            DueDate = new DateTime(2026, 4, 13, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3360),
                            Priority = 3,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Implement authentication",
                            UpdatedDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3360)
                        },
                        new
                        {
                            TaskId = 3,
                            AssignedUserId = 4,
                            CreatedByUserId = 2,
                            CreatedDate = new DateTime(2026, 3, 19, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3370),
                            Description = "Design user interface mockups for all main pages",
                            DueDate = new DateTime(2026, 4, 18, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3360),
                            Priority = 1,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Create UI mockups",
                            UpdatedDate = new DateTime(2026, 3, 19, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3370)
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InAppNotificationsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3120),
                            Department = "IT",
                            DisplayName = "System Administrator",
                            Email = "admin@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Administrator",
                            Role = 3
                        },
                        new
                        {
                            UserId = 2,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3200),
                            Department = "Engineering",
                            DisplayName = "Camille Nicole",
                            Email = "camille.nicole@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Project Manager",
                            Role = 2
                        },
                        new
                        {
                            UserId = 3,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3200),
                            Department = "Engineering",
                            DisplayName = "Floris Kregel",
                            Email = "floris.kregel@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Team Lead",
                            Role = 1
                        },
                        new
                        {
                            UserId = 4,
                            AvailabilityStatus = 0,
                            CreatedDate = new DateTime(2026, 4, 8, 18, 10, 34, 420, DateTimeKind.Utc).AddTicks(3210),
                            Department = "Engineering",
                            DisplayName = "Ni Kang",
                            Email = "ni.kang@contoso.com",
                            EmailNotificationsEnabled = true,
                            InAppNotificationsEnabled = true,
                            JobTitle = "Software Engineer",
                            Role = 0
                        });
                });

            modelBuilder.Entity("ContosoDashboard.Models.Announcement", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ContosoDashboard.Models.DocumentShare", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContosoDashboard.Models.Notification", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("ContosoDashboard.Models.ProjectMember", b =>
                {
                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskComment", b =>
                {
                    b.HasOne("ContosoDashboard.Models.TaskItem", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.HasOne("ContosoDashboard.Models.User", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ContosoDashboard.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ContosoDashboard.Models.Project", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ContosoDashboard.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ContosoDashboard.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTasks");

                    b.Navigation("ManagedProjects");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
